### ISSUE TITLE
A method for running a validation on the date and also a return value if the input is valid or not

### ISSUE THREAD

**Issue by buzzguy** [grantm/jquery-datetextentry#10]
I was wanting to add this date input as a required field before being able to submit a form. 
Is there already an example of this already? 
Otherwise, I imagine a way of doing this would be to run `datetextentry('checkValidation')` on the required field to check if it is filled or not. If it is filled, then the form submits, otherwise, the tooltips show.

**Comment by grantm** [comment]
When you initialise the widget, you can set the option: {required: true}. All this will do is cause the widget to display an error if the user moves the focus into the widget and then moves to another input without entering a valid value.

If a valid date has been entered in the datetextentry widget, then an ISO version of that date (YYYY-MM-DD format) will have been plugged in to the original <input> element that the widget was attached to.

To be absolutely certain that a valid date has been entered, it's up to you to put some logic in the onsubmit event for the form. That logic can retrieve the value from the original <input> element and do whatever you need, such as calling event.preventDefault() to block the form submission; $('#date-input').datetextentry('focus') to move the focus to the widget, etc. It's all up to you :-)
