### ISSUE TITLE
Getting the date value

### ISSUE THREAD

**Issue by StarsoftAnalysis** [grantm/jquery-datetextentry#4]
jquery-datetextentry seems to be just what I've been looking for, except that I can't find a way to get the current value of the field.

There's `$(selector).datetextentry('set_value', '2015-10-13')` but no corresponding `'get_value'`.

That's probably deliberate, expecting that the value will be submitted to the back-end as part of the form, but it's no good for me because I want to get at the date value and do web-socket things with it.

Have I missed something?  

Do you have plans to add a 'get_entry' method?

Regards,

Chris

**Comment by grantm** [comment]
Did you try `$(selector).value()` ?

**Comment by StarsoftAnalysis** [comment]
(You mean `.val()`)

I have now, and yes, `$(selector).val()` does work -- it returns the date as `'yyyy-mm-dd'` (using the default options).

For some reason I thought it would be more complicated than that.

Thanks for your reply.  I've got it working now.
